Repository Does-It-Matters/my-health-block-ap-server, pull requests merged in 2024-09, with the labels that each got.

#128 Add Question JavaDoc 추가
  src/main/java/com/example/myhealthblock/question/adapter/in/web/QuestionController.java
  src/main/java/com/example/myhealthblock/question/adapter/in/web/request/QuestionEnrollRequest.java
  src/main/java/com/example/myhealthblock/question/adapter/in/web/request/QuestionUpdateRequest.java
  src/main/java/com/example/myhealthblock/question/adapter/in/web/response/QuestionListResponse.java
  src/main/java/com/example/myhealthblock/question/adapter/in/web/response/QuestionResponse.java
  src/main/java/com/example/myhealthblock/question/adapter/in/web/response/ResultResponse.java
  src/main/java/com/example/myhealthblock/question/adapter/out/jpa/bodypart/BodyMappingRepository.java
  src/main/java/com/example/myhealthblock/question/adapter/out/jpa/bodypart/BodyPartMapping.java
  src/main/java/com/example/myhealthblock/question/application/port/in/QuestionInputPort.java
  src/main/java/com/example/myhealthblock/question/application/port/in/dto/QuestionEnrollInputPortRequest.java
  src/main/java/com/example/myhealthblock/question/application/port/out/QuestionOutputPort.java
  src/main/java/com/example/myhealthblock/question/application/port/out/dto/QuestionEnrollOutputPortRequest.java
  src/main/java/com/example/myhealthblock/question/application/service/QuestionService.java
  src/main/java/com/example/myhealthblock/question/domain/model/PersonalData.java
  src/main/java/com/example/myhealthblock/question/domain/model/Question.java
Labels: documentation

#130 Add Patient JavaDoc 및 단위테스트/통합테스트 추가
  src/main/java/com/example/myhealthblock/patient/adapter/in/web/PatientController.java
  src/main/java/com/example/myhealthblock/patient/adapter/in/web/response/ResultResponse.java
  src/main/java/com/example/myhealthblock/patient/adapter/out/jpa/PatientEntity.java
  src/main/java/com/example/myhealthblock/patient/adapter/out/jpa/PatientPersistenceAdapter.java
  src/main/java/com/example/myhealthblock/patient/adapter/out/jpa/PatientRepository.java
  src/main/java/com/example/myhealthblock/patient/adapter/out/mybatis/PatientEntity.java
  src/main/java/com/example/myhealthblock/patient/adapter/out/mybatis/PatientMapper.java
  src/main/java/com/example/myhealthblock/patient/application/port/in/PatientInputPort.java
  src/main/java/com/example/myhealthblock/patient/application/port/in/PatientSignUp.java
  src/main/java/com/example/myhealthblock/patient/application/port/in/dto/PatientSignUpInputPortRequest.java
  src/main/java/com/example/myhealthblock/patient/application/port/out/PatientOutputPort.java
  src/test/java/com/example/myhealthblock/doctor/adapter/in/web/DoctorControllerIntegrationTest.java
  src/test/java/com/example/myhealthblock/patient/adapter/out/persistence/PatientEntityTest.java
  src/test/java/com/example/myhealthblock/patient/adapter/out/persistence/PatientPersistenceAdapterIntegrationTest.java
  src/test/java/com/example/myhealthblock/patient/adapter/out/persistence/PatientPersistenceAdapterTest.java
  src/test/java/com/example/myhealthblock/patient/adapter/out/persistence/PatientRepositoryIntegrationTest.java
  src/test/java/com/example/myhealthblock/patient/application/port/in/dto/PatientSignUpInputPortRequestTest.java
  src/test/java/com/example/myhealthblock/patient/application/service/PatientServiceIntegrationTest.java
  src/test/java/com/example/myhealthblock/patient/application/service/PatientServiceTest.java
Labels: documentation, test

#133 Refactor (Issue #80, #131)
  src/main/java/com/example/myhealthblock/user/adapter/out/jpa/UserPersistenceAdapter.java
  src/main/java/com/example/myhealthblock/user/adapter/out/mongodb/UserPersistenceAdapter.java
  src/main/java/com/example/myhealthblock/user/adapter/out/mybatis/UserPersistenceAdapter.java
  src/main/java/com/example/myhealthblock/user/application/service/UserService.java
  src/main/java/com/example/myhealthblock/user/domain/dto/UserDTO.java
  src/main/java/com/example/myhealthblock/user/domain/model/User.java
  src/test/java/com/example/myhealthblock/user/adapter/out/persistence/UserPersistenceAdapterIntegrationTest.java
  src/test/java/com/example/myhealthblock/user/adapter/out/persistence/UserPersistenceAdapterTest.java
  src/test/java/com/example/myhealthblock/user/application/service/UserServiceTest.java
  src/test/java/com/example/myhealthblock/user/domain/model/UserTest.java
Labels: test, refactor

#143 Refactor Patient 모듈 분리 (Issue #137)
  .gitignore
  application/src/main/java/com/example/myhealthblock/patient/adapter/in/web/PatientController.java
  application/src/main/java/com/example/myhealthblock/patient/adapter/in/web/request/PatientSignUpRequest.java
  application/src/test/java/com/example/myhealthblock/patient/adapter/in/web/PatientControllerIntegrationTest.java
  application/src/test/java/com/example/myhealthblock/patient/application/port/in/dto/PatientSignUpInputPortRequestDTOTest.java
  application/src/test/java/com/example/myhealthblock/patient/application/service/PatientServiceIntegrationTest.java
  application/src/test/java/com/example/myhealthblock/patient/application/service/PatientServiceTest.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/in/PatientInputPort.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/in/PatientSignUp.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/in/dto/PatientSignUpInputPortRequest.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/out/PatientOutputPort.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/out/UserSignUpOutputPort.java
  patient-api/src/main/java/com/example/myhealthblock/patient/application/port/out/dto/PatientSignUpOutputPortToUserRequest.java
  patient-api/src/main/java/com/example/myhealthblock/patient/설명.txt
  patient-impl/src/main/java/com/example/myhealthblock/patient/application/port/in/dto/PatientSignUpInputPortRequestDTO.java
  patient-impl/src/main/java/com/example/myhealthblock/patient/application/port/out/dto/PatientSignUpOutputPortToUserRequestDTO.java
  patient-impl/src/main/java/com/example/myhealthblock/patient/application/service/PatientService.java
Labels: refactor

#145 Refactor Doctor impl 분리, api 분리
  application/src/main/java/com/example/myhealthblock/doctor/adapter/in/web/request/DoctorSignUpRequest.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/DoctorInputPort.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/DoctorSignUp.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/GetDoctorProfile.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorProfileInputPortResponse.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorSignUpInputPortRequest.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorSignUpInputPortResponse.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/out/DoctorOutputPort.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/out/UserSignUpOutputPort.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorProfileOutputPortResponse.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorSignUpOutputPortRequest.java
  doctor-api/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorSignUpOutputPortToUserRequest.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorProfileInputPortResponseDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorSignUpInputPortRequestDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/in/dto/DoctorSignUpInputPortResponseDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorProfileOutputPortResponseDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorSignUpOutputPortRequestDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/port/out/dto/DoctorSignUpOutputPortToUserRequestDTO.java
  doctor-impl/src/main/java/com/example/myhealthblock/doctor/application/service/DoctorService.java
  doctor-jpa-adapter/src/main/java/com/example/myhealthblock/doctor/adapter/out/database/jpa/DoctorPersistenceAdapter.java
  doctor-mongo-adapter/src/main/java/com/example/myhealthblock/doctor/adapter/out/database/mongodb/DoctorPersistenceAdapter.java
  doctor-mybatis-adapter/src/main/java/com/example/myhealthblock/doctor/adapter/out/database/mybatis/DoctorPersistenceAdapter.java
Labels: refactor
